name: GitHub Actions Demo

on:
  workflow_dispatch:
  schedule:
    - cron: '15 6 * * SUN'
  push:
    paths-ignore:
      - '.github'
    branches:
      - 'main'

jobs:
  echo:
    name: Echo
    runs-on: ubuntu-latest
    steps:
      - name: Hello
        run: |
          echo "Hello there"