name: GitHub Actions Demo

on:
  workflow_dispatch:
  schedule:
    - cron: '15 6 * * SUN'
  push:
    paths-ignore:
      - '.github/**'
    branches:
      - 'main'

jobs:
  echo:
    name: Echo
    runs-on: ubuntu-latest
    steps:
      - name: Hello
        run: |
          echo "Hello there"
  list:
    name: List
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "${{ github.event_name }}"
          echo "${{ github.ref }}"  
      - uses: actions/checkout@v3.3.0
      - name:
        run: |
          echo "List all"
          ls -la